name: Generate build version
description: ''
inputs:
  sha:
    description: ''
    required: false
outputs:
  version:
    description: ''
    value: ${{ steps.build-version.outputs.version }}
runs:
  using: composite
  steps:
    - id: build-version
      shell: bash
      run: |
        BUILD_DATE=`date "+%FT%H:%M:%S"`
        echo "version={\"build_date\":\"$BUILD_DATE\",\"git_sha\":\"${{ inputs.sha || github.sha }}\"}" >> $GITHUB_OUTPUT
